import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";

const OutfitSans = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${OutfitSans.variable} antialiased`}>{children}</body>
    </html>
  );
}
